### ISSUE TITLE
 Server can NOT start.

### ISSUE THREAD

**Issue by kingcheng2000** [neomjs/create-app#7]
**Describe the bug**
 Server can NOT start.

**To Reproduce**
1.  ubuntu  18.4   
2.  CLI : npm run build-all

**Expected behavior**
server start 

**Screenshots**
at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/home/robot/Documents/workspace/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/robot/Documents/workspace/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/robot/Documents/workspace/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/robot/Documents/workspace/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/robot/Documents/workspace/node_modules/chokidar/lib/nodefs-handler.js:629:21)
(node:29471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject)
(node:29471) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/robot/Documents/workspace/node_modules/css-tree/lib/utils/clone.js'

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04 
 - Browser : chrome
 - Version Version 91.0.4472.164 (Official Build) (64-bit)

**Additional context**

**Comment by tobiu** [comment]
Hi @kingcheng2000,

can you please double-check your versions of node and npm? I have the feeling that they are most likely too old, since chokidar should no longer be used in there.

2 recommendations:
1. using the webpack based server is optional => you can  use a different one (e.g. i am sticking to the webstorm ide which has its own server
2. i just released the neo v3 version and have not found the time yet to update other repos inside the neomjs namespace. since you forked the covid-dashboard: you could fork the neo-repo itself for now, since it contains a newer version of the covid-app inside the apps folder.

best regards,
tobias
